# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        :title

# Setup
title:            Ryan Martz
# tagline:          ''
description:      ""
url:              http://ryanpmartz.com

author:
  name:           'Ryan Martz'
  url:            http://ryanpmartz.com

paginate:         5

# Custom vars
jquery_url:       http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js
